isDeployment: false
proxyDir: /static/proxy
restartServersOnStop: true
serverStartInterval: 30000

http:
  this:
    ip: 0.0.0.0
    port: 3982

  master:
    ip: 0.0.0.0
    port: -1

ftp:
  port: 8633

ident:
  enable: true
  cmd: core ident {}

portMin: 12000
expect: 1